export const SEARCH_TYPE = "SEARCH_TYPE"
export const SEARCH_TEXT = "SEARCH_TEXT"

export const REQUEST_PENDING = "REQUEST_PENDING"
export const REQUEST_SUCCESS = "REQUEST_SUCCESS"
export const REQUEST_FAILED = "REQUEST_FAILED"

export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE"
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE"
export const CLEAR_FAVORITE = "CLEAR_FAVORITE"

export const LOGIN_PENDING = "LOGIN_PENDING"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const LOGOUT = "LOGOUT"